import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { manifestFileName, productName } from "@expojet/brand";
import type { ProjectContext } from "./project.js";

export type CheckStatus = "pass" | "warning" | "fail";
export interface CheckResult {
  name: string;
  status: CheckStatus;
  message: string;
}

function majorMinorPatch(version: string) {
  return version.replace(/^v/, "").split(".").map(Number);
}

const MOBILE_SECRET_PATTERN =
  /CLERK_SECRET_KEY|BETTER_AUTH_SECRET|SUPABASE_SERVICE_ROLE_KEY|DIRECT_DATABASE_URL|JWT_SECRET|JWT_REFRESH_SECRET|(?<!EXPO_PUBLIC_)DATABASE_URL|(?<!EXPO_PUBLIC_)SUPABASE_URL|(?<!EXPO_PUBLIC_)POSTHOG_API_KEY|(?<!EXPO_PUBLIC_)POSTHOG_KEY|(?<!EXPO_PUBLIC_)POSTHOG_SECRET|(?<!EXPO_PUBLIC_)APTABASE_KEY|(?<!EXPO_PUBLIC_)APTABASE_SECRET|SENTRY_AUTH_TOKEN|SENTRY_ORG|SENTRY_PROJECT/;

function treeContains(directory: string, pattern: RegExp): boolean {
  if (!existsSync(directory)) return false;
  return readdirSync(directory, { withFileTypes: true }).some((entry) => {
    if (["node_modules", ".expo", "dist", "dist-ios"].includes(entry.name)) return false;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return treeContains(path, pattern);
    return /\.(?:ts|tsx|js|jsx|json)$/.test(entry.name) && pattern.test(readFileSync(path, "utf8"));
  });
}

export function runDoctorChecks(project: ProjectContext | null): CheckResult[] {
  const [major = 0, minor = 0] = majorMinorPatch(process.version);
  const nodeSupported = major > 22 || (major === 22 && minor >= 12);
  const checks: CheckResult[] = [
    {
      name: "Node.js",
      status: nodeSupported ? "pass" : "fail",
      message: nodeSupported
        ? `${process.version} satisfies >=22.12.0`
        : `${process.version} is below 22.12.0`,
    },
  ];

  if (!project) {
    checks.push({
      name: `${productName} manifest`,
      status: "warning",
      message: `No ${manifestFileName} found in the current directory`,
    });
    return checks;
  }

  checks.push(
    {
      name: `${productName} manifest`,
      status: "pass",
      message: `Schema valid; generated by ${project.manifest.generatorVersion}`,
    },
    {
      name: "Expo SDK pack",
      status: project.manifest.sdk === 57 ? "pass" : "fail",
      message: `SDK ${project.manifest.sdk}`,
    },
  );

  const lockfiles = ["pnpm-lock.yaml", "package-lock.json", "bun.lock", "bun.lockb"].filter(
    (file) => existsSync(join(project.root, file)),
  );
  checks.push({
    name: "Package manager lockfile",
    status: lockfiles.length === 1 ? "pass" : "warning",
    message:
      lockfiles.length === 1
        ? (lockfiles[0] ?? "Lockfile found")
        : `${lockfiles.length} lockfiles found`,
  });

  if (project.manifest.structure === "monorepo" || project.manifest.structure === "monorepo-web") {
    const mobile = join(project.root, "apps/mobile");
    const api = join(project.root, "apps/api");
    const web = join(project.root, "apps/web");
    const isWeb = project.manifest.structure === "monorepo-web";
    const workspacesExist =
      existsSync(join(mobile, "package.json")) &&
      existsSync(join(api, "package.json")) &&
      (!isWeb || existsSync(join(web, "package.json")));
    checks.push({
      name: "Monorepo workspaces",
      status: workspacesExist ? "pass" : "fail",
      message: isWeb
        ? "apps/mobile, apps/api, and apps/web are required"
        : "apps/mobile and apps/api are required",
    });
  }

  const mobileRoot =
    project.manifest.structure === "standalone" ? project.root : join(project.root, "apps/mobile");
  if (existsSync(mobileRoot)) {
    const leaked = treeContains(mobileRoot, MOBILE_SECRET_PATTERN);
    checks.push({
      name: "Mobile secret boundary",
      status: leaked ? "fail" : "pass",
      message: leaked
        ? "Server environment names found in mobile files"
        : "No server environment names found in mobile files",
    });
  }
  if (project.manifest.adapters.auth === "better-auth") {
    checks.push({
      name: "Better Auth promotion",
      status: "warning",
      message: "Experimental until the Expo SDK 57 physical-device gate passes",
    });
  }
  if (project.manifest.adapters.database === "postgres") {
    const hasCompose = existsSync(join(project.root, "docker-compose.yml"));
    checks.push({
      name: "PostgreSQL Docker compose",
      status: hasCompose ? "pass" : "fail",
      message: hasCompose ? "docker-compose.yml found" : "docker-compose.yml missing",
    });
  }
  if (
    project.manifest.adapters.orm === "drizzle" &&
    (project.manifest.structure === "monorepo" || project.manifest.structure === "monorepo-web")
  ) {
    const hasDrizzle = existsSync(join(project.root, "apps/api/drizzle.config.ts"));
    checks.push({
      name: "Drizzle configuration",
      status: hasDrizzle ? "pass" : "fail",
      message: hasDrizzle
        ? "drizzle.config.ts found in apps/api"
        : "drizzle.config.ts missing in apps/api",
    });
  }
  if (project.manifest.adapters.orm === "prisma") {
    const hasPrisma = existsSync(join(project.root, "apps/api/prisma/schema.prisma"));
    checks.push({
      name: "Prisma schema",
      status: hasPrisma ? "pass" : "fail",
      message: hasPrisma
        ? "prisma/schema.prisma found in apps/api"
        : "prisma/schema.prisma missing in apps/api",
    });
  }

  const backend = project.manifest.adapters.backend;
  if (backend === "express") {
    const hasExpressApp = existsSync(join(project.root, "apps/api/src/app.ts"));
    checks.push({
      name: "Express application entrypoint",
      status: hasExpressApp ? "pass" : "fail",
      message: hasExpressApp ? "apps/api/src/app.ts found" : "apps/api/src/app.ts missing",
    });
  } else if (backend === "nestjs") {
    const hasNestMain = existsSync(join(project.root, "apps/api/src/main.ts"));
    const hasNestModule = existsSync(join(project.root, "apps/api/src/app.module.ts"));
    checks.push({
      name: "NestJS application bootstrap",
      status: hasNestMain && hasNestModule ? "pass" : "fail",
      message:
        hasNestMain && hasNestModule
          ? "apps/api/src/main.ts and app.module.ts found"
          : "NestJS entrypoints missing in apps/api",
    });
  } else if (backend === "convex") {
    const isStandalone = project.manifest.structure === "standalone";
    const convexSchemaPath = isStandalone
      ? join(project.root, "convex/schema.ts")
      : join(project.root, "apps/api/convex/schema.ts");
    const hasConvexSchema = existsSync(convexSchemaPath);
    checks.push({
      name: "Convex schema",
      status: hasConvexSchema ? "pass" : "fail",
      message: hasConvexSchema
        ? `${isStandalone ? "convex" : "apps/api/convex"}/schema.ts found`
        : "Convex schema.ts missing",
    });
  }

  const navigation = project.manifest.adapters.navigation ?? "router";
  const navigationType = project.manifest.adapters.navigationType ?? "tabs";

  if (navigation === "react-navigation") {
    const hasRootNav = existsSync(join(mobileRoot, "src/navigation/RootNavigator.tsx"));
    const hasApp = existsSync(join(mobileRoot, "src/App.tsx"));
    checks.push({
      name: "React Navigation entrypoint",
      status: hasRootNav && hasApp ? "pass" : "fail",
      message:
        hasRootNav && hasApp
          ? "src/App.tsx and RootNavigator.tsx found"
          : "React Navigation entrypoints missing in mobile workspace",
    });

    if (navigationType === "both") {
      const hasTabNav = existsSync(join(mobileRoot, "src/navigation/TabNavigator.tsx"));
      checks.push({
        name: "React Navigation TabNavigator",
        status: hasTabNav ? "pass" : "fail",
        message: hasTabNav
          ? "src/navigation/TabNavigator.tsx found"
          : "src/navigation/TabNavigator.tsx missing for 'both' layout",
      });
    }
  } else {
    const hasProtectedLayout = existsSync(join(mobileRoot, "app/(app)/_layout.tsx"));
    checks.push({
      name: "Expo Router protected layout",
      status: hasProtectedLayout ? "pass" : "fail",
      message: hasProtectedLayout
        ? "app/(app)/_layout.tsx found"
        : "app/(app)/_layout.tsx missing in mobile workspace",
    });

    if (navigationType === "both") {
      const hasNestedTabs = existsSync(join(mobileRoot, "app/(app)/(tabs)/_layout.tsx"));
      checks.push({
        name: "Expo Router nested tabs layout",
        status: hasNestedTabs ? "pass" : "fail",
        message: hasNestedTabs
          ? "app/(app)/(tabs)/_layout.tsx found"
          : "app/(app)/(tabs)/_layout.tsx missing for 'both' layout",
      });
    }
  }

  if (project.manifest.adapters.auth === "jwt") {
    const hasClient = existsSync(join(mobileRoot, "src/auth/jwt-client.ts"));
    checks.push({
      name: "JWT auth client",
      status: hasClient ? "pass" : "fail",
      message: hasClient ? "src/auth/jwt-client.ts found" : "JWT auth client missing",
    });
  }

  if (project.manifest.adapters.state === "zustand") {
    const hasStore = existsSync(join(mobileRoot, "src/store/use-app-store.ts"));
    checks.push({
      name: "Zustand store",
      status: hasStore ? "pass" : "fail",
      message: hasStore ? "src/store/use-app-store.ts found" : "Zustand store missing",
    });
  } else if (project.manifest.adapters.state === "mobx") {
    const hasStore = existsSync(join(mobileRoot, "src/store/app-store.ts"));
    checks.push({
      name: "MobX store",
      status: hasStore ? "pass" : "fail",
      message: hasStore ? "src/store/app-store.ts found" : "MobX store missing",
    });
  }

  if (project.manifest.features?.liquidGlass) {
    const hasGlassCard = existsSync(join(mobileRoot, "src/components/ui/glass-card.tsx"));
    checks.push({
      name: "Liquid Glass card",
      status: hasGlassCard ? "pass" : "fail",
      message: hasGlassCard
        ? "src/components/ui/glass-card.tsx found"
        : "GlassCard component missing",
    });

    if (navigationType === "tabs" || navigationType === "both") {
      const tabsPath =
        navigation === "router"
          ? join(
              mobileRoot,
              navigationType === "both" ? "app/(app)/(tabs)/_layout.tsx" : "app/(app)/_layout.tsx",
            )
          : join(
              mobileRoot,
              navigationType === "both"
                ? "src/navigation/TabNavigator.tsx"
                : "src/navigation/AppNavigator.tsx",
            );
      const expectedNativeTabs =
        navigation === "router" ? "<NativeTabs" : "createNativeBottomTabNavigator";
      const hasNativeTabs =
        existsSync(tabsPath) && readFileSync(tabsPath, "utf8").includes(expectedNativeTabs);
      checks.push({
        name: "Native Liquid Glass tabs",
        status: hasNativeTabs ? "pass" : "fail",
        message: hasNativeTabs
          ? "Native tabs enabled for platform Liquid Glass"
          : "Liquid Glass requires the native tabs navigator",
      });
    }
  }

  const analytics = project.manifest.adapters?.analytics;
  if (analytics && analytics !== "none") {
    const hasAnalyticsModule = existsSync(join(mobileRoot, "src/analytics/index.ts"));
    checks.push({
      name: "Mobile analytics module",
      status: hasAnalyticsModule ? "pass" : "fail",
      message: hasAnalyticsModule
        ? "src/analytics/index.ts found"
        : "src/analytics/index.ts missing",
    });

    const hasAnalyticsProvider = existsSync(join(mobileRoot, "src/analytics/provider.tsx"));
    checks.push({
      name: "Mobile analytics provider",
      status: hasAnalyticsProvider ? "pass" : "fail",
      message: hasAnalyticsProvider
        ? "src/analytics/provider.tsx found"
        : "src/analytics/provider.tsx missing",
    });
  }

  const monitoring = project.manifest.adapters?.monitoring;
  if (monitoring && monitoring !== "none") {
    const hasMonitoringInit = existsSync(join(mobileRoot, "src/monitoring/init.ts"));
    checks.push({
      name: "Mobile monitoring init",
      status: hasMonitoringInit ? "pass" : "fail",
      message: hasMonitoringInit
        ? "src/monitoring/init.ts found"
        : "src/monitoring/init.ts missing",
    });

    const hasMonitoringModule = existsSync(join(mobileRoot, "src/monitoring/index.ts"));
    checks.push({
      name: "Mobile monitoring module",
      status: hasMonitoringModule ? "pass" : "fail",
      message: hasMonitoringModule
        ? "src/monitoring/index.ts found"
        : "src/monitoring/index.ts missing",
    });
  }

  if (project.manifest.features?.eas) {
    const easJsonPath = join(mobileRoot, "eas.json");
    const hasEasJson = existsSync(easJsonPath);
    if (!hasEasJson) {
      checks.push({
        name: "EAS Build configuration",
        status: "fail",
        message: "eas.json missing from mobile root",
      });
    } else {
      try {
        const easContent = JSON.parse(readFileSync(easJsonPath, "utf8"));
        const appConfig = JSON.parse(readFileSync(join(mobileRoot, "app.json"), "utf8"));
        const hasBuild =
          typeof easContent === "object" && easContent !== null && "build" in easContent;
        const hasProfiles =
          hasBuild &&
          "development" in easContent.build &&
          "preview" in easContent.build &&
          "production" in easContent.build;

        const hasIdentifiers =
          typeof appConfig?.expo?.ios?.bundleIdentifier === "string" &&
          typeof appConfig?.expo?.android?.package === "string";
        checks.push({
          name: "EAS Build configuration",
          status: hasProfiles && hasIdentifiers ? "pass" : "fail",
          message:
            hasProfiles && hasIdentifiers
              ? "EAS development, preview, and production profiles and native application identifiers are configured"
              : "EAS requires build profiles plus ios.bundleIdentifier and android.package",
        });
      } catch {
        checks.push({
          name: "EAS Build configuration",
          status: "fail",
          message: "eas.json is not valid JSON",
        });
      }
    }
  }

  return checks;
}

function variableNames(source: string) {
  return new Set(
    source
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => line.slice(0, line.indexOf("="))),
  );
}

export interface EnvCheckResult {
  workspace: string;
  variable: string;
  classification: "mobile-public" | "server-secret";
  status: "present" | "missing";
}

export function checkEnvironment(project: ProjectContext): EnvCheckResult[] {
  const workspaces =
    project.manifest.structure === "monorepo-web"
      ? ["apps/mobile", "apps/api", "apps/web"]
      : project.manifest.structure === "monorepo"
        ? ["apps/mobile", "apps/api"]
        : ["."];
  return workspaces.flatMap((workspace) => {
    const directory = workspace === "." ? project.root : join(project.root, workspace);
    const examplePath = join(directory, ".env.example");
    if (!existsSync(examplePath)) return [];
    const required = variableNames(readFileSync(examplePath, "utf8"));
    const actualPath = join(directory, ".env");
    const actual = existsSync(actualPath)
      ? variableNames(readFileSync(actualPath, "utf8"))
      : new Set<string>();
    return [...required].map((variable) => ({
      workspace,
      variable,
      classification: variable.startsWith("EXPO_PUBLIC_")
        ? ("mobile-public" as const)
        : ("server-secret" as const),
      status: actual.has(variable) ? ("present" as const) : ("missing" as const),
    }));
  });
}
