import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { manifestFileName, productName } from "@expojet/brand";
import type { ProjectContext } from "./project.js";

export type CheckStatus = "pass" | "warning" | "fail";
export interface CheckResult {
  name: string;
  status: CheckStatus;
  message: string;
}

function majorMinorPatch(version: string) {
  return version.replace(/^v/, "").split(".").map(Number);
}

function treeContains(directory: string, pattern: RegExp): boolean {
  if (!existsSync(directory)) return false;
  return readdirSync(directory, { withFileTypes: true }).some((entry) => {
    if (["node_modules", ".expo", "dist", "dist-ios"].includes(entry.name)) return false;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return treeContains(path, pattern);
    return /\.(?:ts|tsx|js|jsx|json)$/.test(entry.name) && pattern.test(readFileSync(path, "utf8"));
  });
}

export function runDoctorChecks(project: ProjectContext | null): CheckResult[] {
  const [major = 0, minor = 0] = majorMinorPatch(process.version);
  const nodeSupported = major > 22 || (major === 22 && minor >= 12);
  const checks: CheckResult[] = [
    {
      name: "Node.js",
      status: nodeSupported ? "pass" : "fail",
      message: nodeSupported
        ? `${process.version} satisfies >=22.12.0`
        : `${process.version} is below 22.12.0`,
    },
  ];

  if (!project) {
    checks.push({
      name: `${productName} manifest`,
      status: "warning",
      message: `No ${manifestFileName} found in the current directory`,
    });
    return checks;
  }

  checks.push(
    {
      name: `${productName} manifest`,
      status: "pass",
      message: `Schema valid; generated by ${project.manifest.generatorVersion}`,
    },
    {
      name: "Expo SDK pack",
      status: project.manifest.sdk === 57 ? "pass" : "fail",
      message: `SDK ${project.manifest.sdk}`,
    },
  );

  const lockfiles = ["pnpm-lock.yaml", "package-lock.json", "bun.lock", "bun.lockb"].filter(
    (file) => existsSync(join(project.root, file)),
  );
  checks.push({
    name: "Package manager lockfile",
    status: lockfiles.length === 1 ? "pass" : "warning",
    message:
      lockfiles.length === 1
        ? (lockfiles[0] ?? "Lockfile found")
        : `${lockfiles.length} lockfiles found`,
  });

  if (project.manifest.structure === "monorepo" || project.manifest.structure === "monorepo-web") {
    const mobile = join(project.root, "apps/mobile");
    const api = join(project.root, "apps/api");
    const web = join(project.root, "apps/web");
    const isWeb = project.manifest.structure === "monorepo-web";
    const workspacesExist =
      existsSync(join(mobile, "package.json")) &&
      existsSync(join(api, "package.json")) &&
      (!isWeb || existsSync(join(web, "package.json")));
    checks.push({
      name: "Monorepo workspaces",
      status: workspacesExist ? "pass" : "fail",
      message: isWeb
        ? "apps/mobile, apps/api, and apps/web are required"
        : "apps/mobile and apps/api are required",
    });
    const leaked = treeContains(
      mobile,
      /CLERK_SECRET_KEY|BETTER_AUTH_SECRET|SUPABASE_SERVICE_ROLE_KEY|DIRECT_DATABASE_URL|(?<!EXPO_PUBLIC_)DATABASE_URL|(?<!EXPO_PUBLIC_)SUPABASE_URL/,
    );
    checks.push({
      name: "Mobile secret boundary",
      status: leaked ? "fail" : "pass",
      message: leaked
        ? "Server environment names found in mobile files"
        : "No server environment names found in mobile files",
    });
  }
  if (project.manifest.adapters.auth === "better-auth") {
    checks.push({
      name: "Better Auth promotion",
      status: "warning",
      message: "Experimental until the Expo SDK 57 physical-device gate passes",
    });
  }
  if (project.manifest.adapters.database === "postgres") {
    const hasCompose = existsSync(join(project.root, "docker-compose.yml"));
    checks.push({
      name: "PostgreSQL Docker compose",
      status: hasCompose ? "pass" : "fail",
      message: hasCompose ? "docker-compose.yml found" : "docker-compose.yml missing",
    });
  }
  if (
    project.manifest.adapters.orm === "drizzle" &&
    (project.manifest.structure === "monorepo" || project.manifest.structure === "monorepo-web")
  ) {
    const hasDrizzle = existsSync(join(project.root, "apps/api/drizzle.config.ts"));
    checks.push({
      name: "Drizzle configuration",
      status: hasDrizzle ? "pass" : "fail",
      message: hasDrizzle
        ? "drizzle.config.ts found in apps/api"
        : "drizzle.config.ts missing in apps/api",
    });
  }
  if (project.manifest.adapters.orm === "prisma") {
    const hasPrisma = existsSync(join(project.root, "apps/api/prisma/schema.prisma"));
    checks.push({
      name: "Prisma schema",
      status: hasPrisma ? "pass" : "fail",
      message: hasPrisma
        ? "prisma/schema.prisma found in apps/api"
        : "prisma/schema.prisma missing in apps/api",
    });
  }

  return checks;
}

function variableNames(source: string) {
  return new Set(
    source
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => line.slice(0, line.indexOf("="))),
  );
}

export interface EnvCheckResult {
  workspace: string;
  variable: string;
  classification: "mobile-public" | "server-secret";
  status: "present" | "missing";
}

export function checkEnvironment(project: ProjectContext): EnvCheckResult[] {
  const workspaces =
    project.manifest.structure === "monorepo-web"
      ? ["apps/mobile", "apps/api", "apps/web"]
      : project.manifest.structure === "monorepo"
        ? ["apps/mobile", "apps/api"]
        : ["."];
  return workspaces.flatMap((workspace) => {
    const directory = workspace === "." ? project.root : join(project.root, workspace);
    const examplePath = join(directory, ".env.example");
    if (!existsSync(examplePath)) return [];
    const required = variableNames(readFileSync(examplePath, "utf8"));
    const actualPath = join(directory, ".env");
    const actual = existsSync(actualPath)
      ? variableNames(readFileSync(actualPath, "utf8"))
      : new Set<string>();
    return [...required].map((variable) => ({
      workspace,
      variable,
      classification: variable.startsWith("EXPO_PUBLIC_")
        ? ("mobile-public" as const)
        : ("server-secret" as const),
      status: actual.has(variable) ? ("present" as const) : ("missing" as const),
    }));
  });
}
