import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { ProjectContext } from "./project.js";

export type CheckStatus = "pass" | "warning" | "fail";
export interface CheckResult {
  name: string;
  status: CheckStatus;
  message: string;
}

function majorMinorPatch(version: string) {
  return version.replace(/^v/, "").split(".").map(Number);
}

export function runDoctorChecks(project: ProjectContext | null): CheckResult[] {
  const [major = 0, minor = 0] = majorMinorPatch(process.version);
  const nodeSupported = major > 22 || (major === 22 && minor >= 12);
  const checks: CheckResult[] = [
    {
      name: "Node.js",
      status: nodeSupported ? "pass" : "fail",
      message: nodeSupported
        ? `${process.version} satisfies >=22.12.0`
        : `${process.version} is below 22.12.0`,
    },
  ];

  if (!project) {
    checks.push({
      name: "Stackjet manifest",
      status: "warning",
      message: "No stackjet.jsonc found in the current directory",
    });
    return checks;
  }

  checks.push(
    {
      name: "Stackjet manifest",
      status: "pass",
      message: `Schema valid; generated by ${project.manifest.generatorVersion}`,
    },
    {
      name: "Expo SDK pack",
      status: project.manifest.sdk === 57 ? "pass" : "fail",
      message: `SDK ${project.manifest.sdk}`,
    },
  );

  const lockfiles = ["pnpm-lock.yaml", "package-lock.json", "bun.lock", "bun.lockb"].filter(
    (file) => existsSync(join(project.root, file)),
  );
  checks.push({
    name: "Package manager lockfile",
    status: lockfiles.length === 1 ? "pass" : "warning",
    message:
      lockfiles.length === 1
        ? (lockfiles[0] ?? "Lockfile found")
        : `${lockfiles.length} lockfiles found`,
  });

  return checks;
}

function variableNames(source: string) {
  return new Set(
    source
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => line.slice(0, line.indexOf("="))),
  );
}

export interface EnvCheckResult {
  workspace: string;
  variable: string;
  classification: "mobile-public" | "server-secret";
  status: "present" | "missing";
}

export function checkEnvironment(project: ProjectContext): EnvCheckResult[] {
  const workspaces =
    project.manifest.structure === "monorepo" ? ["apps/mobile", "apps/api"] : ["."];
  return workspaces.flatMap((workspace) => {
    const directory = workspace === "." ? project.root : join(project.root, workspace);
    const examplePath = join(directory, ".env.example");
    if (!existsSync(examplePath)) return [];
    const required = variableNames(readFileSync(examplePath, "utf8"));
    const actualPath = join(directory, ".env");
    const actual = existsSync(actualPath)
      ? variableNames(readFileSync(actualPath, "utf8"))
      : new Set<string>();
    return [...required].map((variable) => ({
      workspace,
      variable,
      classification: variable.startsWith("EXPO_PUBLIC_")
        ? ("mobile-public" as const)
        : ("server-secret" as const),
      status: actual.has(variable) ? ("present" as const) : ("missing" as const),
    }));
  });
}
