export { analyticsAdapter } from "./analytics/index.js";
export { authAdapter } from "./auth/index.js";
export { backendAdapter } from "./backend/index.js";
export type { Adapter, CapabilityDeclaration } from "./contract.js";
export { databaseAdapter } from "./database/index.js";
export { getHapticsAdapter, hapticsAdapter } from "./haptics/index.js";
export { iconAdapter } from "./icons/index.js";
export { getLiquidGlassAdapter, liquidGlassAdapter } from "./liquid-glass/index.js";
export { monitoringAdapter } from "./monitoring/index.js";
export { navigationAdapter } from "./navigation/index.js";
export { ormAdapter } from "./orm/index.js";
export { monorepoPlatformAdapter } from "./platform/index.js";
export { stateAdapter } from "./state/index.js";
export { styleAdapter } from "./style/index.js";
export { themeAdapter } from "./theme/index.js";
